# permissions to do viewer airflowbases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: airflowbase-viewer-role
rules:
- apiGroups:
  - airflow.apache.org
  resources:
  - airflowbases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - airflow.apache.org
  resources:
  - airflowbases/status
  verbs:
  - get
