# permissions to do edit airflowbases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: airflowbase-editor-role
rules:
- apiGroups:
  - airflow.apache.org
  resources:
  - airflowbases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - airflow.apache.org
  resources:
  - airflowbases/status
  verbs:
  - get
  - patch
  - update
